image_width: 600
image_height: 450
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [641.34776,   0.     , 304.04553,
           0.     , 643.24692, 223.75196,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.210673, -0.599123, -0.002493, -0.000794, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [651.71918,   0.     , 303.2931 ,   0.     ,
           0.     , 653.91125, 222.60163,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
