manager:
  ros__parameters:
    # Foxglove:
    websocket: 0
    # Simulation:
    simulation: 0
    gazebo: 0
    simulation_publisher: 0
    ball_count: 0
    device_count: 0
    # Visualisation (optional):
    image_vis: 1
    vector: 1
    filter: 1
    # Config:
    estimator: 1
    width: 1280
    height: 720
    # width: 1920
    # height: 1080
    debug: 0
    # config_path: "/home/ALEX/anytrack/config/positions/mz.json"
    config_path: "/home/ALEX/anytrack/config/positions/kiese.json"
    # config_path: "/home/ALEX/anytrack/config/positions/default.json"
