manager:
  ros__parameters:
    websocket: 0
    gazebo: 1
    simulation: 1
    simulation_publisher: 1
    ball_count: 1
    device_count: 4
    image_vis: 0
    vector: 1
    filter: 0
    estimator: 0
    width: 1280
    height: 720
    debug: 0
    config_path: "/home/ALEX/anytrack/config/positions/sim.json"
