manager:
  ros__parameters:
    websocket: 1
    gazebo: 1
    simulation: 1
    simulation_publisher: 1
    device_count: 4
    image_vis: 1
    vector: 1
    filter: 0
    width: 1280
    height: 720
    debug: 0
    config_path: 1/home/ALEX/anytrack/config/positions/sim.json"
