manager:
  ros__parameters:
    websocket: 0
    gazebo: 0
    simulation: 0
    simulation_publisher: 0
    device_count: 0
    image_vis: 1
    vector: 0
    filter: 1
    width: 1280
    height: 720
    debug: 0
    config_path: "/home/ALEX/anytrack/config/positions/real.json"

