#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit
fi
if [ $1 = "build" ]; then
    echo "Building docker image.."
    key="$(cat ~/.ssh/id_rsa)"
    docker build --build-arg SSH_PRIVATE_KEY="$key" -t rosco-image . 
    docker run -it --name rosco --net=host -v /dev/:/dev --privileged --device /dev/dri/ -e "TERM=xterm-256color" -e DISPLAY=$DISPLAY -v /home/ALEX/anytrack:/home/ALEX/anytrack -v /home/ALEX/anytrack/docker/.zsh_history:/root/.zsh_history:rw -v $HOME/.Xauthority:/root/.Xauthority:ro rosco-image /bin/zsh  
    echo "--------------------done--------------------"
elif [ $1 = "start" ]; then
    echo "starting docker image.."
    xhost +local:docker
    docker start rosco
    echo "--------------------done--------------------"
elif [ $1 = "stop" ]; then
    echo "stoping docker image.."
    docker stop rosco
    echo "--------------------done--------------------"
elif [ $1 = "run" ]; then
    if [ -z "$(docker ps | grep -o "rosco")" ]; then
        echo "starting docker image.."
        xhost +local:docker
        docker start rosco
    fi
    echo "opening cli"
    xhost +local:docker
    if [ $# -eq 2 ]; then
      docker exec -it -w $2 rosco /bin/zsh
    else
      docker exec -it rosco /bin/zsh 
    fi
    echo "--------------------done--------------------"
elif [ $1 = "remove" ]; then
    echo "removing rosco"
    docker stop rosco
    docker rm rosco
    docker image rm rosco-image
    echo "--------------------done--------------------"
else
    echo "what?"
fi
