#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit
fi
if [ $1 = "build" ]; then
    echo "Building docker image.."
    key="$(cat ~/.ssh/id_rsa)"
    docker build --build-arg SSH_PRIVATE_KEY="$key" -t rosco-image . 
    docker run -it --name rosco --net=host --device /dev/video1 --device /dev/video0 --device /dev/dri/ -e "TERM=xterm-256color" -e DISPLAY=$DISPLAY -v /home/ALEX/3dev:/home/ALEX/3dev -v $HOME/.Xauthority:/root/.Xauthority:ro rosco-image /bin/zsh 
    echo "--------------------done--------------------"
elif [ $1 = "start" ]; then
    echo "starting docker image.."
    xhost +local:docker
    docker start rosco
    echo "--------------------done--------------------"
elif [ $1 = "stop" ]; then
    echo "stoping docker image.."
    docker stop rosco
    echo "--------------------done--------------------"
elif [ $1 = "run" ]; then
    echo "opening cli"
    xhost +local:docker
    docker exec -it rosco /bin/zsh
    echo "--------------------done--------------------"
elif [ $1 = "remove" ]; then
    echo "removing rosco"
    docker stop rosco
    docker rm rosco
    docker image rm rosco-image
    echo "--------------------done--------------------"
else
    echo "what?"
fi
