image_width: 600
image_height: 450
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [655.59075,   0.     , 307.55518,
           0.     , 654.22866, 219.83952,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.029978, -0.106374, 0.000363, -0.003313, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [655.67987,   0.     , 305.72336,   0.     ,
           0.     , 655.11652, 219.4393 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
