image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1032.06522,    0.     ,  636.48577,
            0.     , 1028.74567,  369.39421,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.158402, -0.324132, -0.000965, -0.002371, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1045.46985,    0.     ,  632.82976,    0.     ,
            0.     , 1048.25562,  368.39506,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
color:
  start: [42, 140, 95]
  end: [68, 255, 255]
filter:
  contrast: 15
  saturation: 255
