image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [891.8098 ,   0.     , 634.85504,
           0.     , 894.29923, 362.66776,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.011976, -0.043367, 0.000263, 0.003189, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [886.20337,   0.     , 638.77284,   0.     ,
           0.     , 894.92706, 362.32088,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
color:
  start: [42, 140, 95]
  end: [68, 255, 255]
filter:
  contrast: 123
  saturation: 255

